title: Computational imaging
theme: jekyll-theme-cayman
github:
  home: https://captvonsciencypants.github.io/computational-imaging-lab/
  research: https://captvonsciencypants.github.io/computational-imaging-lab/research.html
  people: https://captvonsciencypants.github.io/computational-imaging-lab/people.html
  publications: https://captvonsciencypants.github.io/computational-imaging-lab/publications.html
  software: https://captvonsciencypants.github.io/computational-imaging-lab/software.html
  teaching: https://captvonsciencypants.github.io/computational-imaging-lab/teaching.html
